create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list {dbg_OBUF[6]}]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 192 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {store_adc0/adc_data[0]} {store_adc0/adc_data[1]} {store_adc0/adc_data[2]} {store_adc0/adc_data[3]} {store_adc0/adc_data[4]} {store_adc0/adc_data[5]} {store_adc0/adc_data[6]} {store_adc0/adc_data[7]} {store_adc0/adc_data[8]} {store_adc0/adc_data[9]} {store_adc0/adc_data[10]} {store_adc0/adc_data[11]} {store_adc0/adc_data[12]} {store_adc0/adc_data[13]} {store_adc0/adc_data[14]} {store_adc0/adc_data[15]} {store_adc0/adc_data[16]} {store_adc0/adc_data[17]} {store_adc0/adc_data[18]} {store_adc0/adc_data[19]} {store_adc0/adc_data[20]} {store_adc0/adc_data[21]} {store_adc0/adc_data[22]} {store_adc0/adc_data[23]} {store_adc0/adc_data[24]} {store_adc0/adc_data[25]} {store_adc0/adc_data[26]} {store_adc0/adc_data[27]} {store_adc0/adc_data[28]} {store_adc0/adc_data[29]} {store_adc0/adc_data[30]} {store_adc0/adc_data[31]} {store_adc0/adc_data[32]} {store_adc0/adc_data[33]} {store_adc0/adc_data[34]} {store_adc0/adc_data[35]} {store_adc0/adc_data[36]} {store_adc0/adc_data[37]} {store_adc0/adc_data[38]} {store_adc0/adc_data[39]} {store_adc0/adc_data[40]} {store_adc0/adc_data[41]} {store_adc0/adc_data[42]} {store_adc0/adc_data[43]} {store_adc0/adc_data[44]} {store_adc0/adc_data[45]} {store_adc0/adc_data[46]} {store_adc0/adc_data[47]} {store_adc0/adc_data[48]} {store_adc0/adc_data[49]} {store_adc0/adc_data[50]} {store_adc0/adc_data[51]} {store_adc0/adc_data[52]} {store_adc0/adc_data[53]} {store_adc0/adc_data[54]} {store_adc0/adc_data[55]} {store_adc0/adc_data[56]} {store_adc0/adc_data[57]} {store_adc0/adc_data[58]} {store_adc0/adc_data[59]} {store_adc0/adc_data[60]} {store_adc0/adc_data[61]} {store_adc0/adc_data[62]} {store_adc0/adc_data[63]} {store_adc0/adc_data[64]} {store_adc0/adc_data[65]} {store_adc0/adc_data[66]} {store_adc0/adc_data[67]} {store_adc0/adc_data[68]} {store_adc0/adc_data[69]} {store_adc0/adc_data[70]} {store_adc0/adc_data[71]} {store_adc0/adc_data[72]} {store_adc0/adc_data[73]} {store_adc0/adc_data[74]} {store_adc0/adc_data[75]} {store_adc0/adc_data[76]} {store_adc0/adc_data[77]} {store_adc0/adc_data[78]} {store_adc0/adc_data[79]} {store_adc0/adc_data[80]} {store_adc0/adc_data[81]} {store_adc0/adc_data[82]} {store_adc0/adc_data[83]} {store_adc0/adc_data[84]} {store_adc0/adc_data[85]} {store_adc0/adc_data[86]} {store_adc0/adc_data[87]} {store_adc0/adc_data[88]} {store_adc0/adc_data[89]} {store_adc0/adc_data[90]} {store_adc0/adc_data[91]} {store_adc0/adc_data[92]} {store_adc0/adc_data[93]} {store_adc0/adc_data[94]} {store_adc0/adc_data[95]} {store_adc0/adc_data[96]} {store_adc0/adc_data[97]} {store_adc0/adc_data[98]} {store_adc0/adc_data[99]} {store_adc0/adc_data[100]} {store_adc0/adc_data[101]} {store_adc0/adc_data[102]} {store_adc0/adc_data[103]} {store_adc0/adc_data[104]} {store_adc0/adc_data[105]} {store_adc0/adc_data[106]} {store_adc0/adc_data[107]} {store_adc0/adc_data[108]} {store_adc0/adc_data[109]} {store_adc0/adc_data[110]} {store_adc0/adc_data[111]} {store_adc0/adc_data[112]} {store_adc0/adc_data[113]} {store_adc0/adc_data[114]} {store_adc0/adc_data[115]} {store_adc0/adc_data[116]} {store_adc0/adc_data[117]} {store_adc0/adc_data[118]} {store_adc0/adc_data[119]} {store_adc0/adc_data[120]} {store_adc0/adc_data[121]} {store_adc0/adc_data[122]} {store_adc0/adc_data[123]} {store_adc0/adc_data[124]} {store_adc0/adc_data[125]} {store_adc0/adc_data[126]} {store_adc0/adc_data[127]} {store_adc0/adc_data[128]} {store_adc0/adc_data[129]} {store_adc0/adc_data[130]} {store_adc0/adc_data[131]} {store_adc0/adc_data[132]} {store_adc0/adc_data[133]} {store_adc0/adc_data[134]} {store_adc0/adc_data[135]} {store_adc0/adc_data[136]} {store_adc0/adc_data[137]} {store_adc0/adc_data[138]} {store_adc0/adc_data[139]} {store_adc0/adc_data[140]} {store_adc0/adc_data[141]} {store_adc0/adc_data[142]} {store_adc0/adc_data[143]} {store_adc0/adc_data[144]} {store_adc0/adc_data[145]} {store_adc0/adc_data[146]} {store_adc0/adc_data[147]} {store_adc0/adc_data[148]} {store_adc0/adc_data[149]} {store_adc0/adc_data[150]} {store_adc0/adc_data[151]} {store_adc0/adc_data[152]} {store_adc0/adc_data[153]} {store_adc0/adc_data[154]} {store_adc0/adc_data[155]} {store_adc0/adc_data[156]} {store_adc0/adc_data[157]} {store_adc0/adc_data[158]} {store_adc0/adc_data[159]} {store_adc0/adc_data[160]} {store_adc0/adc_data[161]} {store_adc0/adc_data[162]} {store_adc0/adc_data[163]} {store_adc0/adc_data[164]} {store_adc0/adc_data[165]} {store_adc0/adc_data[166]} {store_adc0/adc_data[167]} {store_adc0/adc_data[168]} {store_adc0/adc_data[169]} {store_adc0/adc_data[170]} {store_adc0/adc_data[171]} {store_adc0/adc_data[172]} {store_adc0/adc_data[173]} {store_adc0/adc_data[174]} {store_adc0/adc_data[175]} {store_adc0/adc_data[176]} {store_adc0/adc_data[177]} {store_adc0/adc_data[178]} {store_adc0/adc_data[179]} {store_adc0/adc_data[180]} {store_adc0/adc_data[181]} {store_adc0/adc_data[182]} {store_adc0/adc_data[183]} {store_adc0/adc_data[184]} {store_adc0/adc_data[185]} {store_adc0/adc_data[186]} {store_adc0/adc_data[187]} {store_adc0/adc_data[188]} {store_adc0/adc_data[189]} {store_adc0/adc_data[190]} {store_adc0/adc_data[191]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {store_adc0/state[0]} {store_adc0/state[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {store_adc0/adc_enb_sr[0]} {store_adc0/adc_enb_sr[1]} {store_adc0/adc_enb_sr[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {store_adc0/sample_num[0]} {store_adc0/sample_num[1]} {store_adc0/sample_num[2]} {store_adc0/sample_num[3]} {store_adc0/sample_num[4]} {store_adc0/sample_num[5]} {store_adc0/sample_num[6]} {store_adc0/sample_num[7]} {store_adc0/sample_num[8]} {store_adc0/sample_num[9]} {store_adc0/sample_num[10]} {store_adc0/sample_num[11]} {store_adc0/sample_num[12]} {store_adc0/sample_num[13]} {store_adc0/sample_num[14]} {store_adc0/sample_num[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list adc0_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list store_adc0/adc_enb_s]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list store_adc0/fifo_wren]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list system_i/zynq_ultra_ps_e_0/U0/pl_clk0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 18 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {store_adc0/fifo_rd_data_cnt[0]} {store_adc0/fifo_rd_data_cnt[1]} {store_adc0/fifo_rd_data_cnt[2]} {store_adc0/fifo_rd_data_cnt[3]} {store_adc0/fifo_rd_data_cnt[4]} {store_adc0/fifo_rd_data_cnt[5]} {store_adc0/fifo_rd_data_cnt[6]} {store_adc0/fifo_rd_data_cnt[7]} {store_adc0/fifo_rd_data_cnt[8]} {store_adc0/fifo_rd_data_cnt[9]} {store_adc0/fifo_rd_data_cnt[10]} {store_adc0/fifo_rd_data_cnt[11]} {store_adc0/fifo_rd_data_cnt[12]} {store_adc0/fifo_rd_data_cnt[13]} {store_adc0/fifo_rd_data_cnt[14]} {store_adc0/fifo_rd_data_cnt[15]} {store_adc0/fifo_rd_data_cnt[16]} {store_adc0/fifo_rd_data_cnt[17]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list store_adc0/fifo_rdstr]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list store_adc0/fifo_trig]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets dbg_OBUF[0]]
